---
- name: Configure Etebase
  become: true
  ansible.builtin.template:
    src: "templates/etebase-server.ini.j2"
    dest: "{{ etebase__user_home }}/etebase_{{ etebase_version_target }}/etebase-server.ini"
    mode: '0640'
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
  register: _etebase_config

- name: "Create static data directorys"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
    recurse: true
    mode: 'u=rwX,g=rX,o=rX'
  with_items:
    - "{{ etebase__global_static_root }}"

- name: "Create media data directorys"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
    recurse: true
    mode: 'u=rwX,g=rX,o='
  with_items:
    - "{{ etebase__global_media_root }}"
    - "{{ etebase__secrets_dir }}"

- name: Deploy yaml file for optional backup support
  become: true
  ansible.builtin.template:
    src: "templates/etebase_version.yml"
    dest: "{{ etebase__user_home }}/etebase_version.yml"
    mode: '0640'
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
