---
- name: "Create EteBase Group"
  become: true
  ansible.builtin.group:
    name: "{{ etebase__group }}"
    system: true
    state: "present"
  notify:
    - "Systemctl restart etebase.service"
    - "Systemctl restart webserver"

- name: "Create Etebase User"
  become: true
  ansible.builtin.user:
    name: "{{ etebase__user }}"
    comment: "Etebase User"
    group: "{{ etebase__group }}"
    groups: "{{ etebase__groups | default(omit) }}"
    home: "{{ etebase__user_home }}"
    shell: "{{ etebase__shell }}"
    system: true
  register: _user
  notify:
    - "Systemctl restart etebase.service"
    - "Systemctl restart webserver"
