---
- name: "Make sure static data is set properly"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
    recurse: true
    mode: 'u=rwX,g=rX,o=rX'
  with_items:
    - "{{ etebase__global_static_root }}"

- name: "Set and cleanup file permissions again"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
    recurse: true
    mode: 'u=rwX,g=rX,o='
  with_items:
    - "{{ etebase__global_media_root }}"
    - "{{ etebase__secrets_dir }}"
    - "{{ etebase__venv }}"
    - "{{ etebase__user_home }}/etebase_{{ etebase_version_target }}"
