---
- name: Run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Create Etebase User/Group
  ansible.builtin.include_tasks: create_user.yml

- name: Define Etebase Version
  ansible.builtin.include_tasks: set_version.yml

- name: Run optional etebase backup
  ansible.builtin.include_tasks: backup.yml
  when: etebase__create_backup | bool

- name: Download Etebase Repo
  ansible.builtin.include_tasks: download.yml

- name: Setup Virtualenv and install Requirements
  ansible.builtin.include_tasks: python_venv.yml

- name: Create Etebase Config
  ansible.builtin.include_tasks: configure.yml

- name: Run ./manage.py migrate
  ansible.builtin.include_tasks: migrate.yml

- name: Setup Systemd Service
  ansible.builtin.include_tasks: systemd.yml
  when: etebase__systemd_setup | bool

- name: Cleanup file permissions
  ansible.builtin.include_tasks: filepermissions.yml
