---
- name: Install Python3 Virtualenv
  become: true
  ansible.builtin.package:
    name: python3-virtualenv
    state: present

- name: Install etebase python requirements in virtualenv
  become: true
  ansible.builtin.pip:
    requirements: "{{ etebase__user_home }}/etebase_{{ etebase_version_target }}/requirements.txt"
    virtualenv: "{{ etebase__venv }}"
    state: "{{ etebase__package_state }}"
    umask: "0027"

- name: Install etebase ASGI Server
  become: true
  ansible.builtin.pip:
    name: 'uvicorn[standard]'
    virtualenv: "{{ etebase__venv }}"
    state: "{{ etebase__package_state }}"
    umask: "0027"

- name: Fix venv File owner/group
  become: true
  ansible.builtin.file:
    path: "{{ etebase__venv }}"
    state: directory
    mode: 'u=rwX,g=rX,o='
    recurse: true
    group: "{{ etebase__group }}"
    owner: "{{ etebase__user }}"
